#!/usr/bin/env python

# https://developer.mozilla.org/en-US/docs/Web/HTML/Element
alltags = {
    'Content sectioning': {
        'headers': '''
            <h2>Header level 2</h2>
            {lorem}

            <h3>Header level 3</h3>
            {lorem}

            <h4>Header level 4</h4>
            {lorem}

            <h5>Header level 5</h5>
            {lorem}

            <h6>Header level 6</h6>
            {lorem}
        ''',

        'aside': '''
            <aside>Some text to the side, see aside.css.</aside>
        ''',
    },

    'Text content': {
        'blockquote': '''
            <blockquote cite="https://www.huxley.net/bnw/four.html">
                <p>Words can be like X-rays, if you use them properly – they'll go through anything. You read and you're pierced.</p>
                <p><cite>– Aldous Huxley, Brave New World</cite></p>
            </blockquote>
        ''',

        'dl': '''
            <p>Cryptids of Cornwall:</p>

            <dl>
                <dt>Beast of Bodmin</dt>
                <dd>A large feline inhabiting Bodmin Moor.</dd>

                <dt>Morgawr</dt>
                <dd>A sea serpent.</dd>

                <dt>Owlman</dt>
                <dd>A giant owl-like creature.</dd>
            </dl>
        ''',

        'figure': '''
            <figure>
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Vincent_van_Gogh_-_Head_of_a_skeleton_with_a_burning_cigarette_-_Google_Art_Project.jpg/579px-Vincent_van_Gogh_-_Head_of_a_skeleton_with_a_burning_cigarette_-_Google_Art_Project.jpg" alt="">
                <figcaption><em>Skull of a Skeleton with Burning Cigarette</em>, by Vincent van Gogh</figcaption>
            </figure>

            {lorem}

            <figure class="border">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project.jpg/1024px-Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project.jpg">
                <figcaption><em>The Tower of Babel</em>, by Pieter Bruegel the Elder</figcaption>
            </figure>

            {lorem}

            <figure class="full">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/The_Garden_of_Earthly_Delights_by_Bosch_High_Resolution.jpg/1280px-The_Garden_of_Earthly_Delights_by_Bosch_High_Resolution.jpg">
                <figcaption><em>The Garden of Earthly Delights</em>, by Hieronymus Bosch</figcaption>
            </figure>

            {lorem}

            <figure class="border full">
                <img
                src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Pieter_Breughel_2%2C_Drunkard_on_an_egg.jpg/1024px-Pieter_Breughel_2%2C_Drunkard_on_an_egg.jpg">
                <figcaption><em>Drunkard on an Egg</em>, by Pieter Brueghel the Younger</figcaption>
            </figure>
        ''',

        'hr': '<hr>',

        'pre': '''
        <pre>if foo:
    bar</pre>
        {lorem}
        <pre class="full">if foo:
    bar</pre>
        ''',
    },

    'Inline text semantics': {
        # <p>This is <abbr title="abbrevation">abbr</abbr>.</p>
        # <p>Inline quote with q: <q cite="https://arp242.net/SOURCE">this is a quote</q>.</p>
        # <p>Mark <mark>this text</mark> with mark element.</p>
        # <p><kbd>Ctrl</kbd> + <kbd>a</kbd></p>
        # <p>The <dfn id="def">dfn</dfn> tag.</p>
        # <p><samp>Sample</samp></p>
        # <p>Small test: <small>Small test</small></p>
        # <p>Super<sup>super</sup> and Sub<sub>sub</sub> text.</p>
        # <p>The concert starts at <time datetime="20:00">20:00</time> and you'll be able to enjoy the band for at least
        # <time datetime="PT2H30M">2h 30m</time>.</p>
        # <p>The volume of a box is <var>l</var> × <var>w</var> × <var>h</var>, where <var>l</var> represents the length,
        # <var>w</var> the width and <var>h</var> the height of the box.</p>
    },

    'Image and multimedia': {
        # audio
        # video
    },

    'Embedded content':  {
        # iframe
    },
    'Scripting': {
        # noscript
    },

    'Demarcating edits': {
        # del, ins
    },

    'Table content': {
    },

    'Forms': {
    },

    'Interactive elements': {
        # details, summary
    },

}

lorem = '''<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
            dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
            sunt in culpa qui officia deserunt mollit anim id est
            laborum.</p>'''

tpl = '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{tag} demo</title>
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="canonical" href="TODO">
    <link rel="stylesheet" href="../base.css">
	<link rel="stylesheet" href="../aside.css">
	<link rel="stylesheet" href="../blockquote.css">
	<link rel="stylesheet" href="../permalink.css">
	<link rel="stylesheet" href="../postscript.css">
</head>

<body>
    <nav class="center">
        <a href="README.html">README</a> |
        <a href="README-fancy.html">Fancier README</a> |
        <a href="index.html">Full demo</a> |
        <a href="http://github.com/Carpetsmoker/hello-css">GitHub</a>
    </nav>

    <article class="page">
        <h1>{tag} demo</h1>
        {lorem}
        {example}
        {lorem}
    </article>
</body>
</html>
'''

index = '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Element demos</title>
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="canonical" href="TODO">
    <link rel="stylesheet" href="../base.css">
</head>

<body>
    <nav class="center">
        <a href="README.html">README</a> |
        <a href="README-fancy.html">Fancier README</a> |
        <a href="index.html">Full demo</a> |
        <a href="http://github.com/Carpetsmoker/hello-css">GitHub</a>
    </nav>

    <article class="page">
        <h1>Element demos</h1>

        <p>This lists the most commonly used elements. Not all of them are
        styled by Hello, CSS; some are just here to check how they look in
        various browsers.</p>

        <p>This is incomplete and work-in-progress.</p>
        <ul>
        {}
        </ul>
    </article>
</body>
</html>
'''

l = ''
for section, tags in alltags.items():
    for tag, example in tags.items():
        with open('./demo/{}.html'.format(tag), 'w') as fp:
            fp.write(tpl.format(tag=tag,
                                example=example.format(lorem=lorem),
                                lorem=lorem))
            l += '<li><a href="{tag}.html">{tag}</a></li>'.format(tag=tag)


with open('./demo/index.html', 'w') as fp:
    fp.write(index.format(l))
