#!/usr/bin/env zsh

# Keep base.css first.
files=(
  base.css
  blockquote.css
  form.css
  permalink.css
  postscript.css
  aside.css
)

: > 'dist/all.min.css'
: > 'dist/all.css'

for f in $files; do
	mf="./dist/$(basename "${f%.css}").min.css"
	cp "$f" "$mf"
	# Note: "Minification" beyond removing comments shaves off very little, and
	# isn't really worth the effort for the vast majority of use cases.
	vim -u NONE --noplugins -NnEs \
      -c ':%s!\s*/\*\(.\|\n\)\{-}\*/! !g' -c ':%s/ *$//' -c ':g/^$/d' -c ':wq' "$mf"

	printf '\n/* FILE: %s */\n' "$f" >> 'dist/all.min.css'
	cat "$mf" >> 'dist/all.min.css'
	cat "$f" >> 'dist/all.css'
done
